travis:
  secure:
    BINSTAR_TOKEN: fzg7ZIT+HNuoMwfSkiwIFLJlFKBRC2d47tw/Dil9QTkvlifghAMRs3hagRhx+lWk2CpYktjgpc75mMjnoFKrciWbirNp0G/Gd7EouwfstCLuU0FW4unwwC5zrMgWZ9w/8hHzmGRKx4NnEMEGyoAqAW+zO78+/vf9Xe9nj/GFL+EDZ/dWO67gvq2YNaEVY+ZuzIlBjdRSJHoRWMX1kI8DtogZkHjRVQpYisLRqeWrJoJrNRhcjmuWXvaCqgbBCJUg8H8jYput32+eK1TAyvmLt8s6K9HjED+7LzTPYvqDAAc/6NWC39srRYezB+O1mvQQl5u9oF4UzwiW+wZn606QH/O2leyw3v3SmbxWzQqcA/cATNw+jnL+NpYd55wi/muPQZYV7RYvPo8hystJvh5plQ3wJsLds7qwdcLQx3RfvRB2PvYiNDxi3nUrylLAjP09vfvIqDLckW7cZNbnKRWVvnkeHXj0vK6SeaBav2EArjnQtAIQouxdbOwpie5pwxU90O7ytr5j85y2GcCKZOIW3M9ZJPbklx+Ly64g4AOCAuXhVXlrrDq+Sdhd6gakx2f63Din1Z0Y3aYJkwI7+2N40fh0u1WSN3Dw3fjXHSLdW/5z3H8YaX9RW2oWZ/94/ggjT2eyVZN4CmFDnNvc22kRi6AqgFT8cCrxrSTdWA0Xg1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
