travis:
  secure:
    BINSTAR_TOKEN: agr4lXStLt8aFCoOYSpI/XhUCOu36+Z0Sgl1jB6U+ynRWnSdU1zzdUul1bemMKvROwwSxL4O/pk81Wtu9SPG/A7v2ZJcWcdoShYrNdW2wuudyDzRcjKrS8ZtqZL3pdAlDVt19ahuzmchgt6+vkQ1rENNO6yiLxqkgdYaVA0uCYQGrURO496wJ/FXXhQSTabVjV9A1u3L+8CXku6mZtckgtGkLzVcH1nc8Zmr/k1mStIt0rUUR+FId8GH4cdSAOp9npnlLjihh4e+rYELJ2r4+UW+rDt+ky2WeIuSu94PDDyfgHCehHuyZ8vks8Yx8e9CNTZ8iu3NdbUsd7g3Hpg45GzvP+dXbereJH8UpsQ4DU5yzjlTsoclSpzrMk2CHzvFjNWI4bFUeQpyZ7LHkxblh/DEku5QhV3zqKCRgYmfQDun7wCBnZFKapJfpvlQHTUvbce8/uRSpRrI+++8m9miEuLpDeSGkXJpqGBAEbXdeUmOUK2WrR22PKmqs2QjWaj3t41MaVsaMEJr24id+QOx52/6hJBgX6KLjHX1WGnCRe/vOj6o5SlNCO9bdEPmY0oqUHgOSXNkci530ZYp5XrtpLEBE1N4fBuehVjLA7SsiPzMsdVTmx0+KvDACSYHCGiLDVheJs8p4RuzqZp2S5Q719aIAGLdJE8hwMi2N6yrFuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
