travis:
  secure:
    BINSTAR_TOKEN: YsFTZNjTVYCpUAPUH6c8r+/YuDMsgwDsmOptFfOWQRNA+sDyqlC0ZXpRPYeQYkF8WXyYTp4UmRKigWjtANs4M/MpLTHAk63IU8QJZ/gm/f3dA82kA2BOxIsjHMk6eVL6g/JEnjT0jZMTKBMfNxLpHe8x5IioMq0MsNpeFmHu/TnYdoSmUjJjQricmBgNIXouKsvFDFghRGEudsZdyPY1XrHik9Umf176gVdvVRrtQZO+fTJ6nAm4g526bOKWM1lkQpAEmrfbcvr0gmscteo/ljAFlj0LLZNUnWt8gYIEa4yTT8PwLexwyIXRqWfvY8VTL2MMVTB3WOirPAbNo1P4h7j+0gOFQQEkj3TnY9OpAkwImfRTX9xpX9ft+msG9iB2mLGJUQgPzOAVtE1O18nVYPPSdmrQoUCtogeXH1yg8OwOYm+i8vwDBRuqoqqKfLNTIIAz6tgnbB2e0y7qkyJaJeU8/QLuxIFxAEs4NukjyKemUVxECpssplVfmM57pZ7OlQUIddFDLHZjn9qvMr8wP48mk4XPcqNPACoXLZT1erPn/2TsPnxwA+3GLGzi/ppP9gL7f8yxbxLsaMO6mBbgMe8QDG8zG5Rhzgo0UN2qy0pHOG+ssLxAb4sHA8ENBi1EVxKIgCVVierIdNwL643HCeXPw5KLb7l1VL7CA0j4nps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
