travis:
  secure:
    BINSTAR_TOKEN: PaaeNG914VGVYKEpMend0mzHkgu86uv1gt4UIEfKsgnuQMtX1RG1Kbs+3Kp4pm5Kf8UhmAUdUKBliSda9VSt2JOnfuGc7aimgLvDDB/+o8E7QrSuA3oquM0xemRCp7o5D+0vQph9javbNDEhFS8OtuOidL16bxwjAo2ItEr2Meap2BRFgjnW+iRp4mjO0kxPySrGgzU3MBZUP/s4+Qh6Ez0HVkoP4hTIh71FU5gX/8KBlYMcpO9HyIGE7BPiVW7ZqhmBphWg6Ps68qmOJ2GHvtNIfjVofIfz6HdSll50PTYLDLW/ctW3GEAcOu9VsExBdXfBT344yCzjzbI0VhMG5eLM6qvSJjN9pCABcsjPF5rkQyOyFL2ismYjOgTPk9DKVomtfch8pRkxeizjwg/jvQdMKmV9w/udGOvDFvXBgLCbThKK6X4N0G8mRf9oTWjlhaG6Zyg7o+lIbLln0oyqEpbtjCwh1fmPmMA5Bm6lDDYLjkkwtfaUb64+tZHB9JjH76w+SQcgC+XoiCnO4rSr84wbQ4OKPgsHir+NeOnpOT5nupvPeHtvErfCYNBwzq0RPY6ELFep9+iMf3DcJi4Sv7pXefHTeWscyDClK1OTH+behdAAH40sQrCAZ213s8O6LnVPp5iXahzudEWFAHbErS1fhJhcioTseETXwZG2ipE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
